name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the container
      run: docker build -t ghcr.io/${{ github.repository_owner }}/test:latest -f ./Dockerfile .

    - name: Login to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Publish
      run: docker push ghcr.io/${{ github.repository_owner }}/test:latest
